name = "ODH Theme by FlashBeing"
license = "MIT"
description = "Theme created by FlashBeing for Open Data Hub Südtirol - Alto Adige"
homepage = "https://flashbeing.com"
min_version = "0.25.1"

[author]
  name = "FlashBeing"
  homepage = "https://flashbeing.com"

# If porting an existing theme
[original]
  author = "freehtml5"
  name = "icon"
  homepage = "https://freehtml5.co/icon-free-website-template-using-bootstrap/"
