name: CI opendatahub-website

on: 
  push:
    branches: [development, master]
    paths:
      - "!README.md"

  pull_request:
    branches: [development, master]
    paths:
      - "!README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
         run: docker build . --file docker/dockerfile-hugo --tag hugo:$(date +%s)